### ISSUE TITLE
Auto-fill credentials

### ISSUE THREAD

**Issue by ryco117** [ryco117/distort-client#5]
When last-login credentials exist, they should populate the input fields. This way if the login is not successful there are relevant values to work with.

**Comment by hjpatel16** [comment]
Hello @ryco117 , Can I work on it?

**Comment by ryco117** [comment]
@hjpatel16 Absolutely! This is my first *real* Android app, so the flow/design may not be perfect. But this should be fairly straightforward to do and I'd love any contributions :) 

This may not be something you can easily test atm though. You'll need a [homeserver](https://github.com/ryco117/distort-server) running, and you may want to look at #6 too because if you don't have a domain name that will be quite limiting.

I recently dockerized the homeserver so that shouldn't be too hard to get running. Let me know if you have any questions!

**Comment by hjpatel16** [comment]
@ryco117 Thanks.. I have homeserver up and running. But I don't have a domain name :( 
Could you please guide me on how to build the client app

**Comment by ryco117** [comment]
@hjpatel16 Glad to hear the server is working! I build the client using Android Studio and then either run the project in a simulator or on my physical Android device. 

Edit: Fixing the IP address issue shouldn't be too hard. I'll fix it if I have time

**Comment by hjpatel16** [comment]
Ok thanks!! I'll start making changes once the client side is up on my physical device.

**Comment by ryco117** [comment]
@hjpatel16 Seem to have fixed #6  (at least for IPv4...) so you can pull and find that much easier.
